export const countryData = [
  { code: "AF", flag: "🇦🇫", name: "Afghanistan", dialCode: "93" },
  { code: "AL", flag: "🇦🇱", name: "Albania", dialCode: "355" },
  { code: "DZ", flag: "🇩🇿", name: "Algeria", dialCode: "213" },
  { code: "AO", flag: "🇦🇴", name: "Angola", dialCode: "244" },
  { code: "AI", flag: "🇦🇮", name: "Anguilla", dialCode: "1264" },
  { code: "AG", flag: "🇦🇬", name: "Antigua and Barbuda", dialCode: "1268" },
  { code: "AR", flag: "🇦🇷", name: "Argentina", dialCode: "54" },
  { code: "AM", flag: "🇦🇲", name: "Armenia", dialCode: "374" },
  { code: "AW", flag: "🇦🇼", name: "Aruba", dialCode: "297" },
  { code: "AU", flag: "🇦🇺", name: "Australia", dialCode: "61" },
  { code: "AT", flag: "🇦🇹", name: "Austria", dialCode: "43" },
  { code: "AZ", flag: "🇦🇿", name: "Azerbaijan", dialCode: "994" },
  { code: "BS", flag: "🇧🇸", name: "Bahamas", dialCode: "1242" },
  { code: "BH", flag: "🇧🇭", name: "Bahrain", dialCode: "973" },
  { code: "BD", flag: "🇧🇩", name: "Bangladesh", dialCode: "880" },
  { code: "BB", flag: "🇧🇧", name: "Barbados", dialCode: "1246" },
  { code: "BY", flag: "🇧🇾", name: "Belarus", dialCode: "375" },
  { code: "BE", flag: "🇧🇪", name: "Belgium", dialCode: "32" },
  { code: "BZ", flag: "🇧🇿", name: "Belize", dialCode: "501" },
  { code: "BJ", flag: "🇧🇯", name: "Benin", dialCode: "229" },
  { code: "BM", flag: "🇧🇲", name: "Bermuda", dialCode: "1441" },
  { code: "BT", flag: "🇧🇹", name: "Bhutan", dialCode: "975" },
  { code: "BO", flag: "🇧🇴", name: "Bolivia", dialCode: "591" },
  { code: "BA", flag: "🇧🇦", name: "Bosnia and Herzegovina", dialCode: "387" },
  { code: "BW", flag: "🇧🇼", name: "Botswana", dialCode: "267" },
  { code: "BR", flag: "🇧🇷", name: "Brazil", dialCode: "55" },
  { code: "BN", flag: "🇧🇳", name: "Brunei", dialCode: "673" },
  { code: "BG", flag: "🇧🇬", name: "Bulgaria", dialCode: "359" },
  { code: "BF", flag: "🇧🇫", name: "Burkina Faso", dialCode: "226" },
  { code: "BI", flag: "🇧🇮", name: "Burundi", dialCode: "257" },
  { code: "KH", flag: "🇰🇭", name: "Cambodia", dialCode: "855" },
  { code: "CM", flag: "🇨🇲", name: "Cameroon", dialCode: "237" },
  { code: "CA", flag: "🇨🇦", name: "Canada", dialCode: "1" },
  { code: "CV", flag: "🇨🇻", name: "Cape Verde", dialCode: "238" },
  { code: "KY", flag: "🇰🇾", name: "Cayman Islands", dialCode: "1345" },
  { code: "CF", flag: "🇨🇫", name: "Central African Republic", dialCode: "236" },
  { code: "TD", flag: "🇹🇩", name: "Chad", dialCode: "235" },
  { code: "CL", flag: "🇨🇱", name: "Chile", dialCode: "56" },
  { code: "CN", flag: "🇨🇳", name: "China", dialCode: "86" },
  { code: "CO", flag: "🇨🇴", name: "Colombia", dialCode: "57" },
  { code: "KM", flag: "🇰🇲", name: "Comoros", dialCode: "269" },
  { code: "CG", flag: "🇨🇬", name: "Republic of the Congo", dialCode: "242" },
  {
    code: "CD",
    flag: "🇨🇩",
    name: "Democratic Republic of the Congo",
    dialCode: "243",
  },
  { code: "CR", flag: "🇨🇷", name: "Costa Rica", dialCode: "506" },
  { code: "CI", flag: "🇨🇮", name: "Ivory Coast", dialCode: "225" },
  { code: "HR", flag: "🇭🇷", name: "Croatia", dialCode: "385" },
  { code: "CU", flag: "🇨🇺", name: "Cuba", dialCode: "53" },
  { code: "CY", flag: "🇨🇾", name: "Cyprus", dialCode: "357" },
  { code: "CZ", flag: "🇨🇿", name: "Czech Republic", dialCode: "420" },
  { code: "DK", flag: "🇩🇰", name: "Denmark", dialCode: "45" },
  { code: "DJ", flag: "🇩🇯", name: "Djibouti", dialCode: "253" },
  { code: "DM", flag: "🇩🇲", name: "Dominica", dialCode: "1767" },
  { code: "DO", flag: "🇩🇴", name: "Dominican Republic", dialCode: "1" },
  { code: "EC", flag: "🇪🇨", name: "Ecuador", dialCode: "593" },
  { code: "EG", flag: "🇪🇬", name: "Egypt", dialCode: "20" },
  { code: "SV", flag: "🇸🇻", name: "El Salvador", dialCode: "503" },
  { code: "GQ", flag: "🇬🇶", name: "Equatorial Guinea", dialCode: "240" },
  { code: "ER", flag: "🇪🇷", name: "Eritrea", dialCode: "291" },
  { code: "EE", flag: "🇪🇪", name: "Estonia", dialCode: "372" },
  { code: "ET", flag: "🇪🇹", name: "Ethiopia", dialCode: "251" },
  { code: "FJ", flag: "🇫🇯", name: "Fiji", dialCode: "679" },
  { code: "FI", flag: "🇫🇮", name: "Finland", dialCode: "358" },
  { code: "FR", flag: "🇫🇷", name: "France", dialCode: "33" },
  { code: "GA", flag: "🇬🇦", name: "Gabon", dialCode: "241" },
  { code: "GM", flag: "🇬🇲", name: "Gambia", dialCode: "220" },
  { code: "GE", flag: "🇬🇪", name: "Georgia", dialCode: "995" },
  { code: "DE", flag: "🇩🇪", name: "Germany", dialCode: "49" },
  { code: "GH", flag: "🇬🇭", name: "Ghana", dialCode: "233" },
  { code: "GR", flag: "🇬🇷", name: "Greece", dialCode: "30" },
  { code: "GD", flag: "🇬🇩", name: "Grenada", dialCode: "1473" },
  { code: "GU", flag: "🇬🇺", name: "Guam", dialCode: "1671" },
  { code: "GT", flag: "🇬🇹", name: "Guatemala", dialCode: "502" },
  { code: "GN", flag: "🇬🇳", name: "Guinea", dialCode: "224" },
  { code: "GW", flag: "🇬🇼", name: "Guinea-Bissau", dialCode: "245" },
  { code: "GY", flag: "🇬🇾", name: "Guyana", dialCode: "592" },
  { code: "HT", flag: "🇭🇹", name: "Haiti", dialCode: "509" },
  { code: "HN", flag: "🇭🇳", name: "Honduras", dialCode: "504" },
  { code: "HK", flag: "🇭🇰", name: "Hong Kong", dialCode: "852" },
  { code: "HU", flag: "🇭🇺", name: "Hungary", dialCode: "36" },
  { code: "IS", flag: "🇮🇸", name: "Iceland", dialCode: "354" },
  { code: "IN", flag: "🇮🇳", name: "India", dialCode: "91" },
  { code: "ID", flag: "🇮🇩", name: "Indonesia", dialCode: "62" },
  { code: "IR", flag: "🇮🇷", name: "Iran", dialCode: "98" },
  { code: "IQ", flag: "🇮🇶", name: "Iraq", dialCode: "964" },
  { code: "IE", flag: "🇮🇪", name: "Ireland", dialCode: "353" },
  { code: "IL", flag: "🇮🇱", name: "Israel", dialCode: "972" },
  { code: "IT", flag: "🇮🇹", name: "Italy", dialCode: "39" },
  { code: "JM", flag: "🇯🇲", name: "Jamaica", dialCode: "1876" },
  { code: "JP", flag: "🇯🇵", name: "Japan", dialCode: "81" },
  { code: "JO", flag: "🇯🇴", name: "Jordan", dialCode: "962" },
  { code: "KZ", flag: "🇰🇿", name: "Kazakhstan", dialCode: "7" },
  { code: "KE", flag: "🇰🇪", name: "Kenya", dialCode: "254" },
  { code: "KI", flag: "🇰🇮", name: "Kiribati", dialCode: "686" },
  { code: "KP", flag: "🇰🇵", name: "North Korea", dialCode: "850" },
  { code: "KR", flag: "🇰🇷", name: "South Korea", dialCode: "82" },
  { code: "KW", flag: "🇰🇼", name: "Kuwait", dialCode: "965" },
  { code: "KG", flag: "🇰🇬", name: "Kyrgyzstan", dialCode: "996" },
  { code: "LA", flag: "🇱🇦", name: "Laos", dialCode: "856" },
  { code: "LV", flag: "🇱🇻", name: "Latvia", dialCode: "371" },
  { code: "LB", flag: "🇱🇧", name: "Lebanon", dialCode: "961" },
  { code: "LS", flag: "🇱🇸", name: "Lesotho", dialCode: "266" },
  { code: "LR", flag: "🇱🇷", name: "Liberia", dialCode: "231" },
  { code: "LY", flag: "🇱🇾", name: "Libya", dialCode: "218" },
  { code: "LI", flag: "🇱🇮", name: "Liechtenstein", dialCode: "423" },
  { code: "LT", flag: "🇱🇹", name: "Lithuania", dialCode: "370" },
  { code: "LU", flag: "🇱🇺", name: "Luxembourg", dialCode: "352" },
  { code: "MO", flag: "🇲🇴", name: "Macau", dialCode: "853" },
  { code: "MK", flag: "🇲🇰", name: "North Macedonia", dialCode: "389" },
  { code: "MG", flag: "🇲🇬", name: "Madagascar", dialCode: "261" },
  { code: "MW", flag: "🇲🇼", name: "Malawi", dialCode: "265" },
  { code: "MY", flag: "🇲🇾", name: "Malaysia", dialCode: "60" },
  { code: "MV", flag: "🇲🇻", name: "Maldives", dialCode: "960" },
  { code: "ML", flag: "🇲🇱", name: "Mali", dialCode: "223" },
  { code: "MT", flag: "🇲🇹", name: "Malta", dialCode: "356" },
  { code: "MH", flag: "🇲🇭", name: "Marshall Islands", dialCode: "692" },
  { code: "MR", flag: "🇲🇷", name: "Mauritania", dialCode: "222" },
  { code: "MU", flag: "🇲🇺", name: "Mauritius", dialCode: "230" },
  { code: "MX", flag: "🇲🇽", name: "Mexico", dialCode: "52" },
  { code: "FM", flag: "🇫🇲", name: "Micronesia", dialCode: "691" },
  { code: "MD", flag: "🇲🇩", name: "Moldova", dialCode: "373" },
  { code: "MC", flag: "🇲🇨", name: "Monaco", dialCode: "377" },
  { code: "MN", flag: "🇲🇳", name: "Mongolia", dialCode: "976" },
  { code: "ME", flag: "🇲🇪", name: "Montenegro", dialCode: "382" },
  { code: "MS", flag: "🇲🇸", name: "Montserrat", dialCode: "1664" },
  { code: "MA", flag: "🇲🇦", name: "Morocco", dialCode: "212" },
  { code: "MZ", flag: "🇲🇿", name: "Mozambique", dialCode: "258" },
  { code: "NA", flag: "🇳🇦", name: "Namibia", dialCode: "264" },
  { code: "NR", flag: "🇳🇷", name: "Nauru", dialCode: "674" },
  { code: "NP", flag: "🇳🇵", name: "Nepal", dialCode: "977" },
  { code: "NL", flag: "🇳🇱", name: "Netherlands", dialCode: "31" },
  { code: "NC", flag: "🇳🇨", name: "New Caledonia", dialCode: "687" },
  { code: "NZ", flag: "🇳🇿", name: "New Zealand", dialCode: "64" },
  { code: "NI", flag: "🇳🇮", name: "Nicaragua", dialCode: "505" },
  { code: "NE", flag: "🇳🇪", name: "Niger", dialCode: "227" },
  { code: "NG", flag: "🇳🇬", name: "Nigeria", dialCode: "234" },
  { code: "NO", flag: "🇳🇴", name: "Norway", dialCode: "47" },
  { code: "OM", flag: "🇴🇲", name: "Oman", dialCode: "968" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan", dialCode: "92" },
  { code: "PW", flag: "🇵🇼", name: "Palau", dialCode: "680" },
  { code: "PS", flag: "🇵🇸", name: "Palestine", dialCode: "970" },
  { code: "PA", flag: "🇵🇦", name: "Panama", dialCode: "507" },
  { code: "PG", flag: "🇵🇬", name: "Papua New Guinea", dialCode: "675" },
  { code: "PY", flag: "🇵🇾", name: "Paraguay", dialCode: "595" },
  { code: "PE", flag: "🇵🇪", name: "Peru", dialCode: "51" },
  { code: "PH", flag: "🇵🇭", name: "Philippines", dialCode: "63" },
  { code: "PL", flag: "🇵🇱", name: "Poland", dialCode: "48" },
  { code: "PT", flag: "🇵🇹", name: "Portugal", dialCode: "351" },
  { code: "PR", flag: "🇵🇷", name: "Puerto Rico", dialCode: "1" },
  { code: "QA", flag: "🇶🇦", name: "Qatar", dialCode: "974" },
  { code: "RE", flag: "🇷🇪", name: "Reunion", dialCode: "262" },
  { code: "RO", flag: "🇷🇴", name: "Romania", dialCode: "40" },
  { code: "RU", flag: "🇷🇺", name: "Russia", dialCode: "7" },
  { code: "RW", flag: "🇷🇼", name: "Rwanda", dialCode: "250" },
  { code: "KN", flag: "🇰🇳", name: "Saint Kitts and Nevis", dialCode: "1869" },
  { code: "LC", flag: "🇱🇨", name: "Saint Lucia", dialCode: "1758" },
  {
    code: "VC",
    flag: "🇻🇨",
    name: "Saint Vincent and the Grenadines",
    dialCode: "1784",
  },
  { code: "WS", flag: "🇼🇸", name: "Samoa", dialCode: "685" },
  { code: "SM", flag: "🇸🇲", name: "San Marino", dialCode: "378" },
  { code: "ST", flag: "🇸🇹", name: "São Tomé and Príncipe", dialCode: "239" },
  { code: "SA", flag: "🇸🇦", name: "Saudi Arabia", dialCode: "966" },
  { code: "SN", flag: "🇸🇳", name: "Senegal", dialCode: "221" },
  { code: "RS", flag: "🇷🇸", name: "Serbia", dialCode: "381" },
  { code: "SC", flag: "🇸🇨", name: "Seychelles", dialCode: "248" },
  { code: "SL", flag: "🇸🇱", name: "Sierra Leone", dialCode: "232" },
  { code: "SG", flag: "🇸🇬", name: "Singapore", dialCode: "65" },
  { code: "SK", flag: "🇸🇰", name: "Slovakia", dialCode: "421" },
  { code: "SI", flag: "🇸🇮", name: "Slovenia", dialCode: "386" },
  { code: "SB", flag: "🇸🇧", name: "Solomon Islands", dialCode: "677" },
  { code: "SO", flag: "🇸🇴", name: "Somalia", dialCode: "252" },
  { code: "ZA", flag: "🇿🇦", name: "South Africa", dialCode: "27" },
  { code: "KR", flag: "🇰🇷", name: "South Korea", dialCode: "82" },
  { code: "SS", flag: "🇸🇸", name: "South Sudan", dialCode: "211" },
  { code: "ES", flag: "🇪🇸", name: "Spain", dialCode: "34" },
  { code: "LK", flag: "🇱🇰", name: "Sri Lanka", dialCode: "94" },
  { code: "SD", flag: "🇸🇩", name: "Sudan", dialCode: "249" },
  { code: "SR", flag: "🇸🇷", name: "Suriname", dialCode: "597" },
  { code: "SZ", flag: "🇸🇿", name: "Eswatini", dialCode: "268" },
  { code: "SE", flag: "🇸🇪", name: "Sweden", dialCode: "46" },
  { code: "CH", flag: "🇨🇭", name: "Switzerland", dialCode: "41" },
  { code: "SY", flag: "🇸🇾", name: "Syria", dialCode: "963" },
  { code: "TW", flag: "🇹🇼", name: "Taiwan", dialCode: "886" },
  { code: "TJ", flag: "🇹🇯", name: "Tajikistan", dialCode: "992" },
  { code: "TZ", flag: "🇹🇿", name: "Tanzania", dialCode: "255" },
  { code: "TH", flag: "🇹🇭", name: "Thailand", dialCode: "66" },
  { code: "TG", flag: "🇹🇬", name: "Togo", dialCode: "228" },
  { code: "TO", flag: "🇹🇴", name: "Tonga", dialCode: "676" },
  { code: "TT", flag: "🇹🇹", name: "Trinidad and Tobago", dialCode: "1868" },
  { code: "TN", flag: "🇹🇳", name: "Tunisia", dialCode: "216" },
  { code: "TR", flag: "🇹🇷", name: "Turkey", dialCode: "90" },
  { code: "TM", flag: "🇹🇲", name: "Turkmenistan", dialCode: "993" },
  { code: "TV", flag: "🇹🇻", name: "Tuvalu", dialCode: "688" },
  { code: "UG", flag: "🇺🇬", name: "Uganda", dialCode: "256" },
  { code: "UA", flag: "🇺🇦", name: "Ukraine", dialCode: "380" },
  { code: "AE", flag: "🇦🇪", name: "United Arab Emirates", dialCode: "971" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom", dialCode: "44" },
  { code: "US", flag: "🇺🇸", name: "United States", dialCode: "1" },
  { code: "UY", flag: "🇺🇾", name: "Uruguay", dialCode: "598" },
  { code: "UZ", flag: "🇺🇿", name: "Uzbekistan", dialCode: "998" },
  { code: "VU", flag: "🇻🇺", name: "Vanuatu", dialCode: "678" },
  { code: "VE", flag: "🇻🇪", name: "Venezuela", dialCode: "58" },
  { code: "VN", flag: "🇻🇳", name: "Vietnam", dialCode: "84" },
  { code: "YE", flag: "🇾🇪", name: "Yemen", dialCode: "967" },
  { code: "ZM", flag: "🇿🇲", name: "Zambia", dialCode: "260" },
  { code: "ZW", flag: "🇿🇼", name: "Zimbabwe", dialCode: "263" },
];

export const getCountryFromPhoneNumber = (phoneNumber) => {
  // Default country code and flag (can be adjusted as needed)
  let defaultCountry = { countryCode: "44", flag: "GB" };

  if (!phoneNumber) return defaultCountry;

  // Check based on the initial digits of the phone number
  for (const country of countryData) {
    if (phoneNumber.startsWith(country.dialCode)) {
      return { countryCode: country.dialCode, flag: country.flag };
    }
  }

  return defaultCountry; // Fallback to default if no match
};

export const formatPhoneNumber = (phoneNumber) => {
  return phoneNumber.replace(/\D/g, ""); // Remove non-digit characters
};
